apps/detector/views.py
import uuid
from pathlib import Path
from werkzeug.utils import secure_filename
from apps.app import db
from apps.crud.models import User
from sqlalchemy import desc, asc
# UploadDiaryFormをimportする
from apps.detector.forms import UploadDiaryForm,SearchDiaryForm
from apps.detector.models import UserImage
from datetime import datetime  # 日付フィールドを扱うためにdatetimeモジュールをインポート
from flask import (
    Flask,
    Blueprint,
    current_app,
    redirect,
    render_template,
    send_from_directory,
    url_for,
    request,
)

# login_required, current_userをimportする
from flask_login import current_user, login_required

# template_folderを指定する（staticは指定しない）
dt = Blueprint("detector", __name__, template_folder="templates")
#今日の日付
current_date = datetime.now().strftime('%Y-%m-%d')
#今日の曜日
current_day = datetime.now().strftime('%a')
def sort_diary():
    diaries = (
        db.session.query(User, UserImage)
        .join(UserImage)
        .filter(User.id == UserImage.user_id)
        .order_by(desc(UserImage.date))  # ここで日付が新しいものが先に来るようにソート
        .all()
    )
    return diaries

def sort_diary_ascending():
    diaries = (
        db.session.query(User, UserImage)
        .join(UserImage)
        .filter(User.id == UserImage.user_id)
        .order_by(asc(UserImage.date))  # ここで日付が昇順にソート
        .all()
    )
    return diaries



# dtアプリケーションを使ってエンドポイントを作成する
@dt.route("/")
@login_required
def index():
    # UserとUserImageをJoinして画像一覧を取得する
    # ソート順を日付が新しいものが先に来るように修正
    form = UploadDiaryForm()
    diaries = sort_diary()
    return render_template("detector/index.html",current_date=current_date,current_day=current_day ,diaries=diaries,form=form)


@dt.route("/images/<path:filename>")
def image_file(filename):
    return send_from_directory(current_app.config["UPLOAD_FOLDER"], filename)


@dt.route("/upload", methods=["GET", "POST"])
# ログイン必須とする
@login_required
def upload_image():

    # UploadDiaryFormを利用してバリデーションをする
    form = UploadDiaryForm()
    if form.validate_on_submit():
        # アップロードされた画像ファイルを取得する
        file = form.image.data

        # ファイルのファイル名と拡張子を取得し、ファイル名をuuidに変換する
        ext = Path(file.filename).suffix
        image_uuid_file_name = str(uuid.uuid4()) + ext

        # 日付データをフォームから取得
        date = form.date.data

        # 日記の文章を取得する
        diary_text = form.diary_text.data

        # # 日付をファイル名に追加する（拡張子を含む）
        # formatted_date = date.strftime('%Y%m%d')
        # image_uuid_file_name = f"{formatted_date}{ext}"

        # 画像を保存する
        image_path = Path(current_app.config["UPLOAD_FOLDER"], image_uuid_file_name)
        file.save(image_path)

        # DBに保存する
        diary = UserImage(user_id=current_user.id, image_path=image_uuid_file_name,date=date,diary_text=diary_text)
        db.session.add(diary)
        db.session.commit()

        return redirect(url_for("detector.index"))
    return render_template("detector/upload.html", form=form)

# dtアプリケーションを使ってエンドポイントを作成する
@dt.route("/all")
@login_required
def all_diary():
    # UserとUserImageをJoinして画像一覧を取得する
    # ソート順を日付が新しいものが先に来るように修正
    diaries = sort_diary()
    return render_template("detector/all.html",current_date=current_date,current_day=current_day ,diaries=diaries)


@dt.errorhandler(404)
def page_not_found(e):
    return render_template("detector/404.html"),404


# 検索ページと検索結果を表示するルート
@dt.route("/", methods=["GET", "POST"])
@login_required
def search_diary():
    form = SearchDiaryForm()
    if request.method == "POST":
        search_term = request.form.get("search_term")
        # SQLiteデータベースから日記を検索するクエリを実行
        diaries = (
            db.session.query(User, UserImage)
            .join(UserImage)
            .filter(User.id == UserImage.user_id)
            .filter(UserImage.diary_text.like(f"%{search_term}%"))  # テキストを検索
            .order_by(desc(UserImage.date))
            .all()
        )
        return render_template("detector/search.html", current_date=current_date, current_day=current_day, diaries=diaries, search_term=search_term,form=form)
    return render_template("detector/search.html", current_date=None, current_day=None, diaries=None, search_term=None,form=form)

# dtアプリケーションを使ってエンドポイントを作成する
@dt.route("/edit/<string:date>", methods=["GET", "POST"])
@login_required
def edit_diary(date):
    form = UploadDiaryForm()
    diaries = (
            db.session.query(User, UserImage)
            .join(UserImage)
            .filter(User.id == UserImage.user_id)
            .filter(date == UserImage.date)
            .all()
        )
    return render_template('detector/edit.html',diaries=diaries,form=form)

# dtアプリケーションを使ってエンドポイントを作成する
@dt.route("/full")
@login_required
def full_diary():
    # UserとUserImageをJoinして画像一覧を取得し、ソート
    diaries = sort_diary_ascending()
    
    # 年ごと、月ごとに日記をグループ化した辞書を作成
    diaries_by_year_and_month = {}
    for diary in diaries:
        year = diary.UserImage.date.year
        month = diary.UserImage.date.month
        if year not in diaries_by_year_and_month:
            diaries_by_year_and_month[year] = {}
        if month not in diaries_by_year_and_month[year]:
            diaries_by_year_and_month[year][month] = []
        diaries_by_year_and_month[year][month].append(diary)

    # 年ごとの日数を計算し、テンプレートに渡す
    year_days = {}
    for year, months in diaries_by_year_and_month.items():
        total_days = 0
        for month, diaries in months.items():
            # 各月の日数を計算して合計に加える
            total_days += len(diaries)
        year_days[year] = total_days

    return render_template("detector/full.html", current_date=current_date, current_day=current_day, diaries_by_year_and_month=diaries_by_year_and_month, year_days=year_days)

# dtアプリケーションを使ってエンドポイントを作成する
@dt.route("/table/<int:date_year>")
@login_required
def table_diary(date_year):
    # UserとUserImageをJoinして画像一覧を取得し、ソート
    diaries = sort_diary_ascending()
    
    # 年ごと、月ごとに日記をグループ化した辞書を作成
    diaries_by_year_and_month = {}
    for diary in diaries:
        year = diary.UserImage.date.year
        month = diary.UserImage.date.month
        if year not in diaries_by_year_and_month:
            diaries_by_year_and_month[year] = {}
        if month not in diaries_by_year_and_month[year]:
            diaries_by_year_and_month[year][month] = []
        diaries_by_year_and_month[year][month].append(diary)

    # 年ごとの日数を計算し、テンプレートに渡す
    year_days = {}
    for year, months in diaries_by_year_and_month.items():
        total_days = 0
        for month, diaries in months.items():
            # 各月の日数を計算して合計に加える
            total_days += len(diaries)
        year_days[year] = total_days
    return render_template('detector/table.html',date_year=date_year, current_date=current_date, current_day=current_day, diaries_by_year_and_month=diaries_by_year_and_month, year_days=year_days)

apps/detector/templates/detector/all.html
{% extends "detector/base.html" %}
{% block content %}
<!-- 画像アップロード画面へのリンクを追加する -->
<div class="col-md-10 text-right dt-image-register-btn">
    <a href="{{ url_for('detector.upload_image') }}" class="btn btn-primary">日記投稿</a>
</div>
<!-- 今日の年月日および曜日を表示する -->
<div class="col-md-5">
    <h2>日記一覧</h2>
</div>
<!-- 画像一覧を表示する -->
{% for diary in diaries %}
    {% if diary.UserImage.date %}
        {% set diary_date = diary.UserImage.date.strftime('%Y-%m-%d') %}
        <div class="card col-md-7 dt-image-content">
            <header class="d-flex justify-content-between">
                <!-- 日付を表示 (存在しない場合は表示しない) -->
                <h2>{{ diary_date }}</h2>
                <hr>
            </header>
            <div class="dt-image-text">
                <p>{{ diary.UserImage.diary_text }}</p>
            </div>
            <section>
                <img src="{{ url_for('detector.image_file', filename=diary.UserImage.image_path) }}" alt="アップロード画像" />
            </section>
        </div>
    {% endif %}
{% endfor %}
{% endblock %}

apps/detector/templates/detector/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <title>10 Year's Diary</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    <link rel="shortcut icon" href="../../../../images/10.ico">
</head>

<body>
    <!-- ナビゲーションバーを作成する -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand " href="{{ url_for('detector.index') }}">10 Year's Diary</a>
            <ul class="navbar-nav">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link">{{ current_user.username }}</span>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('auth.logout') }}" class="nav-link">ログアウト</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">
                        新規登録</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">
                        ログイン</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- block contentをsection class="container"で囲む -->
    <section class="container">
        {% block content %}{% endblock %}
    </section>
    <footer class="footer">
        <div class="container">
            <p>&copy; 2023 10 Year's Diary. All rights reserved.</p>
        </div>
    </footer>
</body>

</html>

apps/detector/templates/detector/edit.html
{% extends "detector/base.html" %}
{% block content %}
<div>
    <h4>投稿編集</h4>
    <form action="{{ url_for('detector.upload_image') }}" method="post" enctype="multipart/form-data"
    novalidate="novalidate">
    {{ form.csrf_token }}
    <input type="date" min="2021-11-20" step="7">
    <input type="date" list="data">
    <datalist id="data">
    <option value="2021-11-05"></option>
    <option value="2021-11-10"></option>
    <option value="2021-11-15"></option>
    </datalist>
    {% for diary in diaries %}
    <div>
        <label>
            <span> {{ form.date(class="form-control-file",value=diary.UserImage.date) }} </span>
        </label>
    </div>
        <div>
            <label>
                <span> {{ form.image(class="form-control-file") }} </span>
            </label>
            <div class="card col-md-7 dt-image-content">
            <section>
                <img src="{{ url_for('detector.image_file', filename=diary.UserImage.image_path) }}" alt="アップロード画像" />
            </section>
            </div>
        </div>

        <div>
            <label>
                {% set f = form.diary_text.process_data(diary.UserImage.diary_text) %}
                <span> {{ form.diary_text(class="form-control") }} </span>
            </label>
            {% for error in form.diary_text.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </div>
        {% for error in form.image.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <hr />
        <div>
            <label> {{ form.submit(class="btn btn-primary") }} </label>
        </div>
    </form>
    {% endfor %}
</div>
{% endblock %}

apps/detector/templates/detector/full.html
{% extends "detector/base.html" %}
{% block content %}
<style>
    /* テーブルを横に並べるためのスタイル */
    body {
        margin: 0;
        padding: 0;
    }
    #table-container {
        margin: -10%;
        margin-left: -160%;
        margin-right: -200%;
        padding: -10%;
        overflow-x: auto; /* 横スクロールを有効にする */
        display: flex; /* テーブルコンテナを水平に並べる */
        font-size:10px
        -webkit-transform:scale(0.4);
        transform:scale(0.4);

    }

    .year-table {
        flex: 0 0 auto; /* テーブルが固定幅で横に並ぶようにする */
        margin-right: 2px; /* テーブル間の間隔を調整 */
        border: 1px solid #ccc; /* テーブルの境界線を追加 */
        padding: 10px; /* テーブル内の余白を調整 */
    }

    /* テーブル内のスタイリング */
    .tablePage {
        width: 100%; /* テーブル幅を100%に設定 */
        border-collapse: collapse; /* セルの境界線を結合 */
    }

    .tablePage th, .tablePage td {
        border: 1px solid #ddd; /* セルの境界線を追加 */
        padding: 8px; /* セル内の余白を調整 */
    }

    @media screen and (max-width:480px){
        #table-container {
            overflow-x: auto; /* 横スクロールを有効にする */
            font-size: 10px;
        }

        .year-table {
            margin-bottom: 20px; /* テーブル間の間隔を調整 */
            border: 1px solid #ccc; /* テーブルの境界線を追加 */
            padding: 10px; /* テーブル内の余白を調整 */
        }

        /* テーブル内のスタイリング */
        .tablePage {
            width: 100%; /* テーブル幅を100%に設定 */
            border-collapse: collapse; /* セルの境界線を結合 */
        }

        .tablePage th, .tablePage td {
            border: 1px solid #ddd; /* セルの境界線を追加 */
            padding: 8px; /* セル内の余白を調整 */
        }
    }
</style>
    <div id="table-container">
        {% for year, year_months in diaries_by_year_and_month.items() %}
            <div class="year-table">
                <h2>{{ year }}</h2>
                <table class="tablePage">
                    <thead>
                        <tr>
                            <th width="40">Month</th>
                            <th width="40">Date</th>
                            <th width="300">Diary Text</th>
                            <th>Image</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for month, month_diaries in year_months.items() %}
                            {% for diary in month_diaries %}
                                <tr>
                                    {% if loop.first %}
                                        <td rowspan="{{ loop.length }}" style="text-align:center;">{{ month }}</td>
                                    {% endif %}
                                    <td style="text-align:center;">{{ diary.UserImage.date.strftime('/ %d') }}</td>
                                    <td>{{ diary.UserImage.diary_text }}</td>
                                    <td style="text-align:center;">
                                        <img src="{{ url_for('detector.image_file', filename=diary.UserImage.image_path) }}" alt="アップロード画像" height=30 px />
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endfor %}
                        <tr>
                            <td colspan="5" style="text-align:right;">Total days in {{ year }}: {{ year_days[year] }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        {% endfor %}
    </div>

    <script>
        // JavaScriptを使って年ごとのテーブルを配置する
        const tableContainer = document.getElementById('table-container');
        const yearTables = document.querySelectorAll('.year-table');

        yearTables.forEach((table, index) => {
            if (index > 0) {
                table.style.display = 'block'; // 2番目以降のテーブルを非表示にする
            }
        });
    </script>
{% endblock %}

apps/detector/templates/detector/index.html
{% extends "detector/base.html" %}
{% block content %}
<!-- 画像アップロード画面へのリンクを追加する -->
<div class="col-md-10 text-right dt-image-register-btn">
    <a href="{{ url_for('detector.upload_image') }}" class="btn btn-primary">日記投稿</a>
</div>
<h1>日記検索</h1>
<form method="POST">
    {{ form.csrf_token }}
    <input type="text" name="search_term"  required="required" placeholder="検索キーワード">
    <input type="submit" value="検索">
</form>
<!-- 今日の年月日および曜日を表示する -->
<div class="col-md-5">
    <h2>Today: {{ current_date }}({{ current_day }})</h2>
</div>
<!-- 画像一覧を表示する -->
{% for diary in diaries %}
    {% if diary.UserImage.date %}
        {% set diary_date = diary.UserImage.date.strftime('%Y-%m-%d') %}
        {% if diary_date[-5:] == current_date[-5:] %}
            <!-- 年月日の後半（月日部分）が一致する場合に表示 -->
            <div class="card col-md-7 dt-image-content">
                <header class="d-flex justify-content-between">
                    <!-- 日付を表示 (存在しない場合は表示しない) -->
                    <h2>{{ diary_date }}</h2>
                    <hr>
                </header>
                <div class="dt-image-text">
                    <p>{{ diary.UserImage.diary_text }}</p>
                </div>
                <section>
                    <img src="{{ url_for('detector.image_file', filename=diary.UserImage.image_path) }}" alt="アップロード画像" />
                </section>
            </div>
        {% endif %}
    {% endif %}
{% endfor %}
{% endblock %}

apps/detector/templates/detector/search.html
{% extends "detector/base.html" %}
{% block content %}
<h1>日記検索</h1>
<form method="POST">
    {{ form.csrf_token }}
    <input type="text" name="search_term" placeholder="検索キーワード">
    <input type="submit" value="検索">
</form>
{% if search_term %}
    <h2>検索結果 for "{{ search_term }}"</h2>
    <!-- 画像一覧を表示する -->
    {% for diary in diaries %}
    {% if diary.UserImage.date %}
        {% set diary_date = diary.UserImage.date.strftime('%Y-%m-%d') %}
        <div class="card col-md-7 dt-image-content">
            <header class="d-flex justify-content-between">
                <!-- 日付を表示 (存在しない場合は表示しない) -->
                <h2>{{ diary_date }}</h2>
                <hr>
            </header>
            <div class="dt-image-text">
                <p>{{ diary.UserImage.diary_text }}</p>
            </div>
            <section>
                <img src="{{ url_for('detector.image_file', filename=diary.UserImage.image_path) }}" alt="アップロード画像" />
            </section>
        </div>
    {% endif %}
    {% endfor %}
{% endif %}
{% endblock %}

apps/detector/templates/detector/table.html
{% extends "detector/base.html" %}
{% block content %}
    <h1>{{ date_year }}年の日記</h1>  <!-- 選択された年を表示 -->
    <div id="table-container">
        {% for year, year_months in diaries_by_year_and_month.items() %}
            {% if year == date_year %}  <!-- 選択された年だけ表示 -->
                <div class="year-table">
                <table class="tablePage">
                    <thead>
                        <tr>
                            <th width="40">Month</th>
                            <th width="40">Date</th>
                            <th>Diary Text</th>
                            <th>Image</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for month, month_diaries in year_months.items() %}
                            {% for diary in month_diaries %}
                                <tr>
                                    {% if loop.first %}
                                        <td rowspan="{{ loop.length }}" style="text-align:center;">{{ month }}</td>
                                    {% endif %}
                                    <td style="text-align:center;">{{ diary.UserImage.date.strftime('/ %d') }}</td>
                                    <td>{{ diary.UserImage.diary_text }}</td>
                                    <td style="text-align:center;">
                                        <img src="{{ url_for('detector.image_file', filename=diary.UserImage.image_path) }}" alt="アップロード画像" height=30 px />
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endfor %}
                        <tr>
                            <td colspan="5" style="text-align:right;">Total days in {{ year }}: {{ year_days[year] }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            {% endif %}
        {% endfor %}
    </div>
    <script>
        // JavaScriptを使って年ごとのテーブルを配置する
        const tableContainer = document.getElementById('table-container');
        const yearTables = document.querySelectorAll('.year-table');

        yearTables.forEach((table, index) => {
            if (index > 0) {
                table.style.display = 'block'; // 2番目以降のテーブルを非表示にする
            }
        });
    </script>
{% endblock %}

apps/detector/templates/detector/upload.html
{% extends "detector/base.html" %}
{% block content %}
<div>
    <h4>新規投稿</h4>
    <form action="{{ url_for('detector.upload_image') }}" method="post" enctype="multipart/form-data"
    novalidate="novalidate">
    {{ form.csrf_token }}
    <input type="date" min="2021-11-20" step="7">
    <input type="date" list="data">
    <datalist id="data">
    <option value="2021-11-05"></option>
    <option value="2021-11-10"></option>
    <option value="2021-11-15"></option>
    </datalist>
    <div>
        <label>
            <span> {{ form.date(class="form-control-file") }} </span>
        </label>
    </div>
        <div>
            <label>
                <span> {{ form.image(class="form-control-file") }} </span>
            </label>
        </div>
        <div>
            <label>
                <span> {{ form.diary_text(class="form-control") }} </span>
            </label>
            {% for error in form.diary_text.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </div>
        {% for error in form.image.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <hr />
        <div>
            <label> {{ form.submit(class="btn btn-primary") }} </label>
        </div>
    </form>
</div>
{% endblock %}