apps/diary/views.py
import logging
# ログの出力名を設定（1）
logger = logging.getLogger('LoggingTest')

# ログをコンソール出力するための設定（2）
sh = logging.StreamHandler()
logger.addHandler(sh)

# log関数でログ出力処理（3）
# logger.log(20, 'info')
# logger.log(30, 'warning')
# logger.log(100, 'test')
import uuid,os
from pathlib import Path
from werkzeug.utils import secure_filename
from apps.app import db
from apps.crud.models import User
from sqlalchemy import desc, asc
# UploadDiaryFormをimportする
from apps.diary.forms import UploadDiaryForm,UpdateDiaryForm,SearchDiaryForm
from apps.diary.models import UserImage
from datetime import datetime, timedelta
from flask_paginate import Pagination, get_page_parameter
from flask import (
  Flask,
  Blueprint,
  current_app,
  redirect,
  render_template,
  send_from_directory,
  url_for,
  request,
  flash
)
import time

# login_required, current_userをimportする
from flask_login import current_user, login_required

# template_folderを指定する（staticは指定しない）
dt = Blueprint("diary", __name__, template_folder="templates")
#今日の日付
current_date = datetime.now().strftime('%Y-%m-%d')
#今日の曜日
current_day = datetime.now().strftime('%a')

#投稿順にソートする
def sort_upload():
    diaries = (
        db.session.query(User, UserImage)
        .join(UserImage)
        .filter(User.id == UserImage.user_id) # ユーザーIDが一致するものを結合
        .filter(User.id == current_user.id)# ログインユーザーのみの日記を表示
        .order_by(desc(UserImage.created_at))  # 投稿順にソート
        .all()
    )
     # 日記データに曜日を追加
    for diary in diaries:
        if diary.UserImage.date:
            diary.UserImage.day_of_week = diary.UserImage.date.strftime('%a')  # 曜日を計算して追加
    return diaries
#編集順にソートする
def sort_update():
    diaries = (
        db.session.query(User, UserImage)
        .join(UserImage)
        .filter(User.id == UserImage.user_id) # ユーザーIDが一致するものを結合
        .filter(User.id == current_user.id)# ログインユーザーのみの日記を表示
        .order_by(desc(UserImage.updated_at))  # 投稿順にソート
        .all()
    )
     # 日記データに曜日を追加
    for diary in diaries:
        if diary.UserImage.date:
            diary.UserImage.day_of_week = diary.UserImage.date.strftime('%a')  # 曜日を計算して追加
    return diaries
#降順にソートする
def sort_diary():
    diaries = (
        db.session.query(User, UserImage)
        .join(UserImage)
        .filter(User.id == UserImage.user_id) # ユーザーIDが一致するものを結合
        .filter(User.id == current_user.id)# ログインユーザーのみの日記を表示
        .order_by(desc(UserImage.date))  # 降順にソート
        .all()
    )
     # 日記データに曜日を追加
    for diary in diaries:
        if diary.UserImage.date:
            diary.UserImage.day_of_week = diary.UserImage.date.strftime('%a')  # 曜日を計算して追加
    return diaries

#昇順にソートする
def sort_diary_ascending():
    diaries = (
        db.session.query(User, UserImage)
        .join(UserImage)
        .filter(User.id == UserImage.user_id)
        .filter(User.id == current_user.id)
        .order_by(asc(UserImage.date))  # 昇順にソート
        .all()
    )
    for diary in diaries:
        if diary.UserImage.date:
            diary.UserImage.day_of_week = diary.UserImage.date.strftime('%a')  
    return diaries

# すべての日付を返す
def get_existent_dates():
    exist_dates =[]
    diaries = (
        db.session.query(UserImage.date)
        .filter(User.id == UserImage.user_id)
        .filter(User.id == current_user.id)
        .join(User)
        .order_by(UserImage.date)
    )
    exist_dates = [date[0] for date in diaries.distinct()]
    return exist_dates
# 最新の日付を返す
def get_latest_date():
    latest_date = (
        db.session.query(UserImage.date)
        .join(User)
        .filter(User.id == UserImage.user_id)       
        .filter(User.id == current_user.id)
        .order_by(UserImage.date.desc())  # 降順に並べ替える
        .first()
    )
    if latest_date:
        latest_date = latest_date[0]  # latest_dateを日付オブジェクトに変換
        next_date = latest_date + timedelta(days=1)  # 1日を加算
        return next_date
    else:
        return None

def getAll():
    diaries = sort_diary()
    diaries_by_year_and_month = {}
    for diary in diaries:
        year = diary.UserImage.date.year
        month = diary.UserImage.date.month
        diaries_by_year_and_month.setdefault(year, {}).setdefault(month, []).append(diary)

    year_days = {year: sum(len(month_diaries) for month_diaries in months.values()) for year, months in diaries_by_year_and_month.items()}
    return (diaries_by_year_and_month, year_days)
def getAllas():
    diaries = sort_diary_ascending()
    diaries_by_year_and_month = {}
    for diary in diaries:
        year = diary.UserImage.date.year
        month = diary.UserImage.date.month
        diaries_by_year_and_month.setdefault(year, {}).setdefault(month, []).append(diary)

    year_days = {year: sum(len(month_diaries) for month_diaries in months.values()) for year, months in diaries_by_year_and_month.items()}
    return (diaries_by_year_and_month, year_days)
# dtアプリケーションを使ってエンドポイントを作成する
@dt.route("/")
#ログインが必要
@login_required
def index():
    # UserとUserImageをJoinして画像一覧を取得する
    form = UploadDiaryForm()
    diaries = sort_diary()
    return render_template("diary/index.html",current_date=current_date,current_day=current_day ,diaries=diaries,form=form)

#画像を表示するルート
@dt.route("/images/<path:filename>")
@login_required
def image_file(filename):
    user_id = current_user.id 
    user_directory = os.path.join(current_app.config["UPLOAD_FOLDER"], str(user_id))
    return send_from_directory(user_directory, filename)

#日記をアップロードするルート
@dt.route("/upload", methods=["GET", "POST"])
@login_required
#日記をアップロード
def upload_diary():
    form = UploadDiaryForm()
    exist_dates = get_existent_dates()
    latest_date = get_latest_date()
    date = form.date.data
    diary_text = form.diary_text.data

    if form.validate_on_submit():
        if date in exist_dates:
            flash('その日付の日記は既に存在します', 'error')
            return  redirect(url_for("diary.edit_diary",date= date))
        else:
            if form.image.data is not None:
                # 画像がアップロードされている場合の処理
                user_directory = os.path.join(current_app.config["UPLOAD_FOLDER"], str(current_user.id))
                os.makedirs(user_directory, exist_ok=True)
                file = form.image.data
                ext = Path(file.filename).suffix
                image_uuid_file_name = str(uuid.uuid4()) + ext
                image_path = os.path.join(user_directory, image_uuid_file_name)
                file.save(image_path)

                # DBに保存する
                diary = UserImage(user_id=current_user.id, image_path=image_uuid_file_name, date=date, diary_text=diary_text)
            else:
                # 画像がアップロードされていない場合の処理
                diary = UserImage(user_id=current_user.id, image_path=None, date=date, diary_text=diary_text)

            db.session.add(diary)
            db.session.commit()
            return redirect(url_for("diary.all_diary"))
    return render_template("diary/upload.html", form=form, exist_dates=exist_dates, latest_date=latest_date)

#日付を降順にして表示するルート
@dt.route("/all")
@login_required
def all_diary():
    diaries = sort_update()
    # 日記の総数を取得
    length = len(diaries)
    # ページネーション
    ## 現在のページ番号を取得
    page = int(request.args.get(get_page_parameter(), 1))
    ## ページごとの表示件数
    per_page = 18
    ## ページネーションオブジェクトを作成
    pagination = Pagination(page=page, per_page=per_page, total=length)
    # 表示するデータを取得
    start = (page - 1) * per_page
    end = start + per_page
    displayed_menu = diaries[start:end]
    return render_template("diary/all.html",current_date=current_date,length=length, diaries=displayed_menu, pagination=pagination)

@dt.errorhandler(404)
def page_not_found(e):
    return render_template("diary/404.html"),404


# 検索ページと検索結果を表示するルート
@dt.route("/", methods=["GET", "POST"])
@login_required
def search_diary():
    form = SearchDiaryForm()
    if request.method == "POST":
        # SQLiteデータベースから日記を検索するクエリを実行
        diaries = (
            db.session.query(User, UserImage)
            .join(UserImage)
            .filter(User.id == UserImage.user_id)
            .filter(User.id == current_user.id)
            .order_by(desc(UserImage.date))
        )
        search_term = request.form.get("search_term")
        search_date_str = request.form.get("search_date")
        if not search_date_str or search_term:
            flash("どちらかを選択してください", "danger")
            return redirect(url_for("diary.search_diary"))
        if search_date_str:
            try:
                search_date = datetime.strptime(search_date_str, "%Y-%m-%d").date()
                diaries = diaries.filter(UserImage.date == search_date)
            except ValueError:
                return redirect(url_for("search_diary"))
        if search_term:
            diaries = diaries.filter(UserImage.diary_text.like(f"%{search_term}%"))
        diaries = diaries.order_by(desc(UserImage.date)).all()
        return render_template("diary/search.html", current_date=current_date, current_day=current_day, diaries=diaries, search_term=search_term,form=form,search_date=search_date)
    return render_template("diary/search.html", current_date=None, current_day=None, diaries=None, search_term=None,form=form)

@dt.route("/table")
@login_required
def table_diary():
    diaries_by_year_and_month, year_days = getAll()
    return render_template('diary/table.html', diaries_by_year_and_month=diaries_by_year_and_month, year_days=year_days)

@dt.route("/table/full")
@login_required
def full_diary():
    diaries_by_year_and_month, year_days = getAllas()
    return render_template("diary/full.html", diaries_by_year_and_month=diaries_by_year_and_month,
    year_days=year_days)

@dt.route("/table/<int:date_year>")
@login_required
def tableY_diary(date_year):
    diaries_by_year_and_month, year_days = getAllas()
    return render_template('diary/tableY.html', date_year=date_year, diaries_by_year_and_month=diaries_by_year_and_month, year_days=year_days)

@dt.route("/diaries/<string:date>")
@login_required
def view_diaries(date):

apps/diary/templates/diary/all.html
{% extends "diary/base.html" %}
{% block content %}
<!-- 画像アップロード画面へのリンクを追加する -->
<div class="col-md-3 dt-image-register-btn" id="diary-upload">
    <a href="{{ url_for('diary.upload_diary') }}" class="btn btn-diary opacity-80" >日記投稿</a>
</div>
<div class="col-md-3 dt-image-register-btn" id="diary-goup">
</div>
<!-- 今日の年月日および曜日を表示する -->
<div class="col-md-5">
    <h3>最新の日記</h3>
</div>
<!-- 画像一覧を表示する -->
<div class="row">
{% for diary in diaries %}
    {% if diary.UserImage.date %}
        {% set diary_date = diary.UserImage.date.strftime('%Y-%m-%d') %}
        <div class="card col-lg-2  dt-image-content" id="diaryAll">
            <header class="d-flex justify-content-between" >
                <!-- 日付を表示 (存在しない場合は表示しない) -->
                <h6 id="allDate">{{ diary_date }}</h6>
                <h6 class="allDay">(</h6>
                {% if diary.UserImage.day_of_week == 'Sat' %}
                    <h6 class="allDaySaturday">{{ diary.UserImage.day_of_week }}</h6> <!-- 曜日を表示 -->
                {% elif diary.UserImage.day_of_week == 'Sun' %}
                    <h6 class="allDaySunday">{{ diary.UserImage.day_of_week }}</h6> <!-- 曜日を表示 -->
                {% else %}
                    <h6 class="allDay">{{ diary.UserImage.day_of_week }}</h6> <!-- 曜日を表示 -->
                {% endif %}
                <h6 class="allDay">)</h6>
                <hr/>
            </header>
            <div class="dt-image-text" id="allImagetext">
                <p >{{ diary.UserImage.diary_text }}</p>
            </div>
            <a href="{{ url_for('diary.edit_diary', date=diary_date) }}"></a>

            {% if diary.UserImage.image_path %}
            <img class="my-auto" src="{{ url_for('diary.image_file', user_id=diary.UserImage.user_id, filename=diary.UserImage.image_path) }}" alt="アップロード画像" />
            {% else %}
                <p></p>
            {% endif %}
            </div>
    {% endif %}
{% endfor %}
</div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-auto">
            {{ pagination.links }}
        </div>
    </div>
</div>
{% endblock %}

apps/diary/templates/diary/edit.html
{% extends "diary/base.html" %}
{% block content %}
<div>
    <!-- Flashメッセージを表示 -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <div class="alert alert-{{ messages[0][0] }} text-danger mt-3" >
            {{ messages[0][1] }}
        </div>
    {% endif %}
    {% endwith %}

    <h4>投稿編集</h4>
    <form class=" center-block text-center mt-5" action="{{ url_for('diary.edit_diary', date=diary.UserImage.date) }}" method="post" enctype="multipart/form-data"
    novalidate="novalidate">
    {{ form.csrf_token }}
    <label>
        <span>{{ form.date(class="form-control-file", value=diary.UserImage.date) }}</span>
    </label>
    <div>
        <div class="my-3" id="testForm">
            <label class="mx-auto" for="formSelect" id="fileLabel">
              <span>{{ form.image(class="form-control-file", id="formSelect") }}ファイルを選択</span>
            </label>
            <p id="fileName" style="display: none;"></p>
            <div id="imageContainer" style="display: none;">
                <img id="selectedImage" src="" alt="Selected Image" class="img-fluid " style="max-width: 400px; max-height: 400px;">
            </div>
          </div>
        <div class="img-fluid" id="editImage" >
            <section>
                {% if diary.UserImage.image_path %}
                <img src="{{ url_for('diary.image_file',  user_id=diary.UserImage.user_id,filename=diary.UserImage.image_path) }}" alt="アップロード画像" style="max-width: 400px; max-height: 400px;"/>
                {% else %}
                    <p>写真が投稿されていません</p>
                {% endif %}
            </section>
        </div>
    </div>
    <p>投稿内容</p>
    <div>
        <label class="mx-auto">
            <textarea class="form-control" id="exampleFormControlTextarea1" name="diary_text" rows="10" value = "" style="width: 350px; height: 200px;" placeholder="投稿内容" >{{diary.UserImage.diary_text}}</textarea>
        </label>
        {% for error in form.diary_text.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </div>
    <hr />
    <div>
        <label class="mx-5">{{ form.delete(class="btn btn-danger") }}</label>
        <label class="mx-5">{{ form.submit(class="btn btn-diary ") }}</label>
    </div>
    </form>
</div>
{% endblock %}

apps/diary/templates/diary/flash.html
<!doctype html>
<meta http-equiv="refresh" content=" 3; url=./">
<title>My Application</title>
<h1>エラー</h1>
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
<div id="countdown" style="display: inline;">3 秒後に自動的にリダイレクトされます。</div>
{% block body %}{% endblock %}
<script>
    var countdownElement = document.getElementById('countdown');
    var count = parseInt(countdownElement.innerHTML);

    function updateCountdown() {
        if (count > 0) {
            count--;
            countdownElement.innerHTML = count + ' 秒後に自動的にリダイレクトされます。';
        }
    }

    var countdownInterval = setInterval(updateCountdown, 1000);
</script>

apps/diary/templates/diary/full.html
{% extends "diary/base.html" %}
{% block content %}
<style>
    /* テーブルを横に並べるためのスタイル */
    body {
        margin: 0;
        padding: 0;
    }

    #table-container {
        display: flex; /* テーブルコンテナを水平に並べる */
    }

    .year-table {
        width: 100%; /* テーブルが親要素いっぱいに広がるようにする */
        margin-right: 2px; /* テーブル間の間隔を調整 */
        border: 1px solid #ccc; /* テーブルの境界線を追加 */
        padding: 10px; /* テーブル内の余白を調整 */
    }

    /* テーブル内のスタイリング */
    .tablePage {
        width: 100%; /* テーブル幅を100%に設定 */
        border-collapse: collapse; /* セルの境界線を結合 */
        font-size: 6px; /* フォントサイズを調整 */
    }

    .tablePage th, .tablePage td {
        border: 1px solid #ddd; /* セルの境界線を追加 */
        padding: 2px; /* セル内の余白を調整 */
        text-align: center; /* テキストを中央寄せにする */
    }

    .tablePage th:nth-child(1),
    .tablePage td:nth-child(1),
    .tablePage th:nth-child(2),
    .tablePage td:nth-child(2) {
        width: 10%; /* 月と日の列の幅を調整 */
    }

    .tablePage th:nth-child(3),
    .tablePage td:nth-child(3) {
        width: 40%; /* テキストの列の幅を調整 */
    }

    .tablePage th:nth-child(4),
    .tablePage td:nth-child(4) {
        width: 40%; /* 画像の列の幅を調整 */
    }

    @media screen and (max-width:480px){
        .year-table {
            margin-bottom: 10px; /* テーブル間の間隔を調整 */
            border: 1px solid #ccc; /* テーブルの境界線を追加 */
            padding: 5px; /* テーブル内の余白を調整 */
        }

        /* テーブル内のスタイリング */
        .tablePage {
            font-size: 6px; /* フォントサイズを調整 */
        }

        .tablePage th, .tablePage td {
            border: 1px solid #ddd; /* セルの境界線を追加 */
            padding: 2px; /* セル内の余白を調整 */
        }
    }
</style>




    <div style="transform-origin: top left;transform:scale(.6);" id="table-container">
        {% for year, year_months in diaries_by_year_and_month.items() %}
            <div class="year-table">
                <h2>{{ year }}</h2>
                <table class="tablePage">
                    <thead>
                        <tr>
                            <th width="40">Month</th>
                            <th width="40">Date</th>
                            <th width="300">Diary Text</th>
                            <th>Image</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for month, month_diaries in year_months.items() %}
                            {% for diary in month_diaries %}
                                <tr>
                                    {% if loop.first %}
                                        <td rowspan="{{ loop.length }}" style="text-align:center;">{{ month }}</td>
                                    {% endif %}
                                    <td style="text-align:center;">{{ diary.UserImage.date.strftime('/ %d') }}</td>
                                    <td style="min-width: 100px;">{{ diary.UserImage.diary_text }}</td>
                                    <td style="text-align:center;">
                                        {% if diary.UserImage.image_path %}
                                        <img src="{{ url_for('diary.image_file', user_id=diary.UserImage.user_id, filename=diary.UserImage.image_path) }}" alt="アップロード画像"  height=30 px/>
                                        {% else %}
                                            <p></p>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endfor %}
                        <tr>
                            <td colspan="5" style="text-align:right;">Total days in {{ year }}: {{ year_days[year] }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        {% endfor %}
    </div>

    <script>
        // JavaScriptを使って年ごとのテーブルを配置する
        const tableContainer = document.getElementById('table-container');
        const yearTables = document.querySelectorAll('.year-table');

        yearTables.forEach((table, index) => {
            if (index > 0) {
                table.style.display = 'block'; // 2番目以降のテーブルを非表示にする
            }
        });
    </script>
{% endblock %}

apps/diary/templates/diary/index.html
{% extends "diary/base.html" %}
{% block content %}
<div class="flash-messages">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-danger">
                <ul class="my-auto">
                    {% for message in messages %}
                        <li >{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    {% endwith %}
</div>
<div class="search">
    <h5 class="d-flex align-items-center my-2" id="diary-search">日記検索</h5>
    <form method="POST" class="row align-items-center" id="indexInput">
        {{ form.csrf_token }}
        <input class="col-md-4" type="text" name="search_term" placeholder="検索キーワード">
        <input class="col-md-4"type="date" name="search_date" class="form-control" placeholder="日付を選択">
        <input class="col-md-4"type="submit" value="検索">
    </form>
</div>



<!-- 画像アップロード画面へのリンクを追加する -->
<div class="col-md-3 dt-image-register-btn opacity-80" id="diary-upload">
    <a href="{{ url_for('diary.upload_diary') }}" class="btn btn-diary  " >日記投稿</a>
</div>
<!-- 今日の年月日および曜日を表示する -->
<div class="col-md-5">
    <h4 id="today">Today: {{ current_date }}({{ current_day }})</h4>
</div>

<!-- 画像一覧を表示する -->
{% for diary in diaries %}
    {% if diary.UserImage.date %}
        {% set diary_date = diary.UserImage.date.strftime('%Y-%m-%d') %}
        {% if diary_date[-5:] == current_date[-5:] %}
            <!-- 年月日の後半（月日部分）が一致する場合に表示 -->
            <div class="card col-md-7 dt-image-content" id="diary-post">
                <header class="d-flex justify-content-between">
                    <!-- 日付を表示 (存在しない場合は表示しない) -->
                    <h4>{{ diary_date }}</h4>
                    <hr>
                </header>
                <div class="dt-image-text mx-2">
                    <p>{{ diary.UserImage.diary_text }}</p>
                </div>
                <a href="{{ url_for('diary.edit_diary', date=diary_date) }}"></a>
                <section>
                    {% if diary.UserImage.image_path %}
                    <img src="{{ url_for('diary.image_file', user_id=diary.UserImage.user_id, filename=diary.UserImage.image_path) }}" alt="アップロード画像" />
                    {% else %}
                        <p></p>
                    {% endif %}
                </section>
            </div>
        {% endif %}
    {% endif %}
{% endfor %}

{% endblock %}

apps/diary/templates/diary/reupload.html
{% extends "diary/base.html" %}
{% block content %}
<div>
    <h4>新規投稿</h4>
    <form action="{{ url_for('diary.upload_diary') }}" method="post" enctype="multipart/form-data"
    novalidate="novalidate">
    {{ form.csrf_token }}
    <input type="date" min="2021-11-20" step="7">
    <input type="date" list="data">
    <datalist id="data">
    <option value="2021-11-05"></option>
    <option value="2021-11-10"></option>
    <option value="2021-11-15"></option>
    {% for exist_date in exist_dates %}
        <option value="{{ exist_date }}">{{ exist_date }}</option>
    {% endfor %}
    </datalist>

    <div>
        <label>
            <span> {{ form.date(class="form-control-file", default=latest_date) }} </span>
        </label>
    </div>
        <div>
            <label>
                <span> {{ form.image(class="form-control-file") }} </span>
            </label>
        </div>
        <div>
            <label>
                <span> {{ form.diary_text(class="form-control") }} </span>
            </label>
            {% for error in form.diary_text.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </div>
        {% for error in form.image.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <hr />
        <div>
            <label> {{ form.submit(class="btn btn-primary") }} </label>
        </div>
    </form>
</div>
{% endblock %}

apps/diary/templates/diary/search.html
{% extends "diary/base.html" %}
{% block content %}
<h1>日記検索</h1>
<form method="POST">
    {{ form.csrf_token }}
    <input type="text" name="search_term" placeholder="検索キーワード">
    <input type="date" name="search_date" class="form-control" placeholder="日付を選択">
    <input type="submit" value="検索">
</form>
{% if diaries %}
    <h2>検索結果</h2>
    <!-- 画像一覧を表示する -->
    {% if diaries %}
        {% for diary in diaries %}
        {% if diary.UserImage.date %}
            {% set diary_date = diary.UserImage.date.strftime('%Y-%m-%d') %}
            <div class="card col-md-7 dt-image-content">
                <header class="d-flex justify-content-between">
                    <!-- 日付を表示 (存在しない場合は表示しない) -->
                    <h2>{{ diary_date }}</h2>
                    <hr>
                </header>
                <div class="dt-image-text">
                    <p>{{ diary.UserImage.diary_text }}</p>
                </div>
                <section>
                    <img src="{{ url_for('diary.image_file', user_id=diary.UserImage.user_id, filename=diary.UserImage.image_path) }}" alt="アップロード画像" />
                </section>
            </div>
        {% endif %}
        {% endfor %}
    {% endif %}
{% else %}
    <h2 class=" mt-5 mb-5  text-center">該当する投稿なし</h2>
{% endif %}
{% endblock %}

apps/diary/templates/diary/single.html
{% extends "diary/base.html" %}
{% block content %}
<!-- 画像アップロード画面へのリンクを追加する -->
<div class="col-md-10 text-right dt-image-register-btn">
    <a href="{{ url_for('diary.upload_diary') }}" class="btn btn-primary">日記投稿</a>
</div>
<!-- 画像一覧を表示する -->
    {% if diary.UserImage.date %}
        {% set diary_date = diary.UserImage.date.strftime('%Y-%m-%d') %}
        <div class="card col-md-7 dt-image-content">
            <header class="d-flex justify-content-between">
                <!-- 日付を表示 (存在しない場合は表示しない) -->
                <h2>{{ diary_date }}</h2>
                <h  r>
            </header>
            <div class="dt-image-text">
                <p>{{ diary.UserImage.diary_text }}</p>
            </div>
            <section>
                <img src="{{ url_for('diary.image_file',  user_id=diary.UserImage.user_id,filename=diary.UserImage.image_path) }}" alt="アップロード画像" />
            </section>
        </div>
    {% endif %}
{% endblock %}

apps/diary/templates/diary/table.html
{% extends "diary/base.html" %}
{% block content %}
    <h5 class="mt-5 text-center">アーカイブ</h5>
    <ul id="year-list" class="mt-5">
        {% for year, year_months in diaries_by_year_and_month.items() %}
          <li class="card mt-1">
            <a class="card-body text-dark" href="{{ url_for('diary.tableY_diary', date_year=year) }}">{{ year }}</a>
          </li>
        {% endfor %}
    </ul>

{% endblock %}

apps/diary/templates/diary/upload.html
{% extends "diary/base.html" %}
{% block content %}
<div>
    <!-- Flashメッセージを表示 -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <div class="alert alert-{{ messages[0][0] }} text-danger mt-3" >
            {{ messages[0][1] }}
        </div>
    {% endif %}
    {% endwith %}


    <h4 class="mt-4 text-center">新規投稿</h4>
    <form class=" center-block text-center mt-5" method="POST" enctype="multipart/form-data" >
        {{ form.csrf_token }}
        <label>
            <span>{{ form.date(class="form-control-file", value=latest_date) }}</span>
        </label>
        <div class="my-3" id="testForm">
            <label class="mx-auto" for="formSelect" id="fileLabel">
                <span>{{ form.image(class="form-control-file", id="formSelect") }}ファイルを選択</span>
            </label>
            <p id="fileName" style="display: none;"></p>
            <div id="imageContainer" style="display: none;">
                <img id="selectedImage" src="" alt="Selected Image" class="img-fluid " style="max-width: 400px; max-height: 400px;">
            </div>

        </div>
        {% for error in form.image.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <div class="mb-3 ">
            <div>
                <label class="mx-auto">
                    <textarea class="form-control" id="exampleFormControlTextarea1" name="diary_text" rows="10" value = "" style="width: 350px; height: 200px;" placeholder="投稿内容" ></textarea>
                </label>
            </div>
        </div>
        {% for error in form.diary_text.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <hr />
        <div class="mt-5 text-right">
            <label>{{ form.submit(class="btn btn-diary") }}</label>
        </div>
    </form>

{% endblock %}